### ISSUE TITLE
Insert saved values in a model

### ISSUE THREAD

**Issue by lordhagen94** [javierluraschi/nomnoml#24]
I built a model for my thesis with nomnoml and I am really satisfied with the looks. Now I want to add the specific path coefficients (see exapmle below). The thing is, that I want the model  to adapt if the values for the path coefficients change. Therefore I don't want to type "0.27" into the nomnoml model but use the saved value "a1" instead. So when "a1" for example changes to "0.21" that I don't have to change the value in the model but it changes automatically.  Is there a way to do this in nomnoml? Also is it possible to center the inserted value in the middle of the arrow line?
Thanks in advance

`

```{r data}

a1 <- 0.27
b1 <- 0.35
```

```{nomnoml, svg=TRUE}
#stroke: black
#ranker: longest-path
#spacing: 40
#gravity: 2
#edges:hard
#arrowSize: 0.8
#lineWidth: 2
#padding: 12


[Social Comparison]<--[<reference>Age]
[FOMO]<--[<reference>Age]
[SNS Addiction]<--[<reference>Age]

[FOMO]<--[<reference>Gender]
[Social Comparison]<--[<reference>Gender]



[Subjective Well-Being]->[Social Comparison]
[Social Comparison]->[FOMO]
[FOMO]->[SNS Addiction]
[Subjective Well-Being]->[SNS Addiction]



```

`

**Comment by andrie** [comment]
The `nomnoml` library does not have a concept of macro substitution, so you will have to write this yourself.

Since the `nomnoml` model is plain text, you could use `glue::glue()` to insert text into your model.

For example:

```r
a <- 0.27

nomnoml(glue::glue("
[x] -> [a = {a}]
"))
```

![image](https://user-images.githubusercontent.com/479998/154331524-6022354b-ce60-4c96-a30b-2035c67a62b3.png)


To label an arrow:

```r
nomnoml(glue::glue("
[x] -> {a} [a]
"))
```

![image](https://user-images.githubusercontent.com/479998/154331766-31153163-29ab-49e8-aad6-03813a028d6a.png)
